services:
  nginx:
    build: ./requirements/nginx/.
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - web:/var/www/html
    networks:
      inception:
    env_file:
      - .env
  wordpress:
    build: ./requirements/wordpress/.
    container_name: wordpress
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - web:/var/www/html
    networks:
      inception:
    env_file:
      - .env
  mariadb:
    build: ./requirements/mariadb/.
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    networks:
      inception:
    volumes:
      - database:/var/lib/mysql
    env_file:
      - .env
# optional, just to check that user was created
# grep alive needed since mysqladmin returns 0 for any response
    healthcheck:
      test: mysqladmin ping -h localhost -u${DB_USER} -p${DB_PASS} | grep alive
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  database:
    name: database
    driver: local
    driver_opts:
      device: ${DATA_DIR}/database
      o: bind
      type: none
  web:
    name: web
    driver: local
    driver_opts:
      device: ${DATA_DIR}/web
      o: bind
      type: none

networks:
  inception:
    name: inception